In [1]:
# libraries
#importing necessary packages for the assignment
import os
from datetime import datetime
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from PIL import Image
import urllib
from random import choices
from itertools import chain
# Levenshtein Distance in Python
# https://github.com/seatgeek/thefuzz
from thefuzz import fuzz, process

# Matplotlib configuration
font = { 'family': 'DejaVu Sans', 'weight': 'bold', 'size': 16 }
plt.rc('font', **font)

# Pandas config
pd.options.mode.chained_assignment = None  # default='warn'




from functools import wraps
import types

from pyspark.conf import SparkConf
from pyspark.context import SparkContext
from pyspark.rdd import RDD, RDDBarrier
from pyspark.files import SparkFiles
from pyspark.storagelevel import StorageLevel
from pyspark.accumulators import Accumulator, AccumulatorParam
from pyspark.broadcast import Broadcast
from pyspark.serializers import MarshalSerializer, PickleSerializer
from pyspark.status import *
from pyspark.taskcontext import TaskContext, BarrierTaskContext, BarrierTaskInfo
from pyspark.profiler import Profiler, BasicProfiler
from pyspark.version import __version__
from pyspark._globals import _NoValue



import time
import re
import pandas as pd
import numpy as np
import jellyfish as jf
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from sklearn.dummy import DummyClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.linear_model import Perceptron
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score



#MLlib
#machiine learning API for spark

from __future__ import print_function
from pyspark.mllib.recommendation import ALS, MatrixFactorizationModel, Rating


import numpy as np
import pandas as pd
import pickle
import vaderSentiment
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import pyplot
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from sklearn.model_selection import train_test_split
import spacy
nlp = spacy.load("en_core_web_sm")
import gc
gc.collect()
# set random seed
np.random.seed(seed=42)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel
from sklearn.cluster import MiniBatchKMeans
from skimpy import clean_columns
from sentence_transformers import SentenceTransformer
import matplotlib.pyplot as plt
from fuzzywuzzy import process, fuzz
model = SentenceTransformer('bert-base-nli-mean-tokens')
import pandas as pd
import keras
from keras import Sequential, layers, regularizers, optimizers
import numpy as np
from string import punctuation
import pyprind
from collections import Counter
from keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from scipy import stats
from natsort import natsorted,ns

import numpy as np
import pandas as pd
import re
import nltk
from nltk.stem.snowball import SnowballStemmer
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from nltk import sent_tokenize
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import HashingVectorizer, TfidfVectorizer
from sklearn.pipeline import make_pipeline
from sklearn.pipeline import FeatureUnion, Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn import svm
import csv
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import Normalizer

C:\ProgramData\Anaconda3\lib\site-packages\thefuzz\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
C:\ProgramData\Anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [2]:
import numpy as np
import pandas as pd
import re
# To process englishwritten in the datset (natural language processing)
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to C:\Users\VISHANG
[nltk_data]     MEHTA\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\VISHANG
[nltk_data]     MEHTA\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.feature_extraction.text import CountVectorizer
from collections import Counter

import pandas as pd
import numpy as np
import sklearn.preprocessing, sklearn.decomposition, sklearn.linear_model, sklearn.pipeline, sklearn.metrics, sklearn.compose
from sklearn.feature_extraction.text import CountVectorizer

# Import package/module for data
import numpy as np
import pandas as pd
from seaborn import load_dataset

# Import modules for feature engineering and modelling
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn import datasets

In [7]:
#calling the training parquet file in which processing has to be done
offers_training_df = pd.read_parquet('offers_training.parquet')

In [8]:
f'Number of products in training: {len(offers_training_df):,}'

'Number of products in training: 102,884'

In [31]:
list(offers_training_df.columns)

['offer_id',
 'shop',
 'lang',
 'brand',
 'color',
 'title',
 'description',
 'price',
 'url',
 'image_urls']

In [12]:
# splitting the dataset to 2 dataset based on shop
#1- zalondo
#2- aboutyou

offers_training_df_zalondo = offers_training_df[offers_training_df['shop'] == 'zalando']
offers_training_df_zalondo.head()

,offer_id,shop,lang,brand,color,title,description,price,url,image_urls
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,zalando,de,Guess,weiß,JUNIOR REVERSIBLE HOODED LONG Wintermantel,skirt_details Eingrifftaschen | Ziersteine $ n...,150.685455,https://www.zalando.de/lookup/article/GU123L05...,[https://img01.ztat.net/article/1ec35ff491c54e...
8,08c47691-4160-41df-81c5-ea108f2ae539,zalando,de,Ellesse,weiß,HOLLINA SHIRT & LEGGING Pyjama Nachtwäsche Set,name_suffix white $ pattern print $ material.u...,39.958182,https://www.zalando.de/lookup/article/EL981P00...,[https://img01.ztat.net/article/511a8191c10549...
11,96fc5065-3a31-42f0-bfbd-34ee94324807,zalando,de,Selected,blau,SLHSLIMMARK WASHED Businesshemd,main_supplier_code K70240 $ name_suffix dark s...,39.990909,https://www.zalando.de/lookup/article/SE622D0Y...,[https://img01.ztat.net/article/4ca1292819fa35...
12,04341c9e-4043-4478-9a64-266ac38480b5,zalando,de,Ellesse,schwarz,NURRA FASHION TRUNKS 5 PACK Panties,main_supplier_code K10441 $ name_suffix black ...,32.958182,https://www.zalando.de/lookup/article/EL982O00...,[https://img01.ztat.net/article/ca67693a608332...
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,zalando,de,Selected,braun,SLFOLIVE CARDIGAN Strickjacke,name_suffix carafe $ pattern meliert $ materia...,89.990909,https://www.zalando.de/lookup/article/SE521I0P...,[https://img01.ztat.net/article/a797f668349e4d...

In [14]:
offers_training_df_aboutyou= offers_training_df[offers_training_df['shop'] == 'aboutyou']
offers_training_df_aboutyou.head()

,offer_id,shop,lang,brand,color,title,description,price,url,image_urls
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,aboutyou,de,PIECES,hellblau | Blau,Kleid,"{""Material"": [""Baumwolle""], ""\u00c4rmell\u00e4...",24.99,https://www.aboutyou.de/p/pieces/kleid-6732409,[https://cdn.aboutstatic.com/file/images/06728...
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,aboutyou,de,LASCANA,schwarz | mischfarben | Schwarz,Bikinihose,"{""Leibh\u00f6he"": [""Super Low Waist""], ""Marke""...",34.90,https://www.aboutyou.at/p/lascana/bikinihose-5...,[https://cdn.aboutstatic.com/file/8ba09c163f54...
2,f0328791-9839-4bc1-ac62-78b7515e9601,aboutyou,de,MAMALICIOUS,beige | Beige,Chino-Hose,"{""Marke"": [""MAMALICIOUS""], ""Gr\u00f6\u00dfenla...",21.99,https://www.aboutyou.de/p/mamalicious/chino-ho...,[https://cdn.aboutstatic.com/file/images/90ddf...
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,aboutyou,de,rosemunde,rosa | Pink,Top / Seidentop,"{""Marke"": [""rosemunde""], ""Zielgruppe"": [""Femal...",49.99,https://www.aboutyou.de/p/rosemunde/top-seiden...,[https://cdn.aboutstatic.com/file/images/3cf28...
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,aboutyou,de,PIECES,mischfarben | schwarz | Mischfarben | Schwarz,Kleid,"{""\u00c4rmell\u00e4nge"": [""Langarm""], ""Ausschn...",39.90,https://www.aboutyou.at/p/pieces/kleid-5195289,[https://cdn.aboutstatic.com/file/images/c85d6...

In [15]:
# keeping the columns which are necessary for the completion of the challenge
# and removing rest of the columns 

offers_training_df_zalondo_1 = offers_training_df_zalondo [['offer_id', 'brand', 'color', 'title']]
offers_training_df_zalondo_1.head()

,offer_id,brand,color,title
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,Guess,weiß,JUNIOR REVERSIBLE HOODED LONG Wintermantel
8,08c47691-4160-41df-81c5-ea108f2ae539,Ellesse,weiß,HOLLINA SHIRT & LEGGING Pyjama Nachtwäsche Set
11,96fc5065-3a31-42f0-bfbd-34ee94324807,Selected,blau,SLHSLIMMARK WASHED Businesshemd
12,04341c9e-4043-4478-9a64-266ac38480b5,Ellesse,schwarz,NURRA FASHION TRUNKS 5 PACK Panties
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,Selected,braun,SLFOLIVE CARDIGAN Strickjacke

In [16]:
offers_training_df_aboutyou_1 = offers_training_df_aboutyou [['offer_id', 'brand', 'color', 'title']]
offers_training_df_aboutyou_1.head(5)

,offer_id,brand,color,title
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,PIECES,hellblau | Blau,Kleid
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,LASCANA,schwarz | mischfarben | Schwarz,Bikinihose
2,f0328791-9839-4bc1-ac62-78b7515e9601,MAMALICIOUS,beige | Beige,Chino-Hose
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunde,rosa | Pink,Top / Seidentop
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,PIECES,mischfarben | schwarz | Mischfarben | Schwarz,Kleid

In [17]:
# concatenating the columns 'brand', 'color' and 'title'

offers_training_df_zalondo_1["Name"] = offers_training_df_zalondo_1["brand"] + offers_training_df_zalondo_1["color"] +  offers_training_df_zalondo_1["title"]

In [18]:
offers_training_df_zalondo_1.head()

,offer_id,brand,color,title,Name
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,Guess,weiß,JUNIOR REVERSIBLE HOODED LONG Wintermantel,GuessweißJUNIOR REVERSIBLE HOODED LONG Winterm...
8,08c47691-4160-41df-81c5-ea108f2ae539,Ellesse,weiß,HOLLINA SHIRT & LEGGING Pyjama Nachtwäsche Set,EllesseweißHOLLINA SHIRT & LEGGING Pyjama Nach...
11,96fc5065-3a31-42f0-bfbd-34ee94324807,Selected,blau,SLHSLIMMARK WASHED Businesshemd,SelectedblauSLHSLIMMARK WASHED Businesshemd
12,04341c9e-4043-4478-9a64-266ac38480b5,Ellesse,schwarz,NURRA FASHION TRUNKS 5 PACK Panties,EllesseschwarzNURRA FASHION TRUNKS 5 PACK Panties
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,Selected,braun,SLFOLIVE CARDIGAN Strickjacke,SelectedbraunSLFOLIVE CARDIGAN Strickjacke

In [19]:
offers_training_df_aboutyou_1["Name"] = offers_training_df_aboutyou_1["brand"] + offers_training_df_aboutyou_1["color"] +  offers_training_df_aboutyou_1["title"]

In [20]:
offers_training_df_aboutyou_1.head()

,offer_id,brand,color,title,Name
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,PIECES,hellblau | Blau,Kleid,PIECEShellblau | BlauKleid
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,LASCANA,schwarz | mischfarben | Schwarz,Bikinihose,LASCANAschwarz | mischfarben | SchwarzBikinihose
2,f0328791-9839-4bc1-ac62-78b7515e9601,MAMALICIOUS,beige | Beige,Chino-Hose,MAMALICIOUSbeige | BeigeChino-Hose
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunde,rosa | Pink,Top / Seidentop,rosemunderosa | PinkTop / Seidentop
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,PIECES,mischfarben | schwarz | Mischfarben | Schwarz,Kleid,PIECESmischfarben | schwarz | Mischfarben | Sc...

In [22]:
# keeping the combined column with offer_id

offers_training_df_zalondo_2 = offers_training_df_zalondo_1 [['offer_id', 'Name']]
offers_training_df_zalondo_2.head()

,offer_id,Name
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,GuessweißJUNIOR REVERSIBLE HOODED LONG Winterm...
8,08c47691-4160-41df-81c5-ea108f2ae539,EllesseweißHOLLINA SHIRT & LEGGING Pyjama Nach...
11,96fc5065-3a31-42f0-bfbd-34ee94324807,SelectedblauSLHSLIMMARK WASHED Businesshemd
12,04341c9e-4043-4478-9a64-266ac38480b5,EllesseschwarzNURRA FASHION TRUNKS 5 PACK Panties
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,SelectedbraunSLFOLIVE CARDIGAN Strickjacke

In [23]:
offers_training_df_aboutyou_2 = offers_training_df_aboutyou_1 [['offer_id', 'Name']]
offers_training_df_aboutyou_2.head()

,offer_id,Name
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,PIECEShellblau | BlauKleid
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,LASCANAschwarz | mischfarben | SchwarzBikinihose
2,f0328791-9839-4bc1-ac62-78b7515e9601,MAMALICIOUSbeige | BeigeChino-Hose
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunderosa | PinkTop / Seidentop
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,PIECESmischfarben | schwarz | Mischfarben | Sc...

In [24]:
offers_training_df_zalondo_1['comparison1'] = offers_training_df_zalondo_1['brand'].str.cat(offers_training_df_zalondo_1['color'],sep=" ")
offers_training_df_zalondo_1.head(6)

,offer_id,brand,color,title,Name,comparison1
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,Guess,weiß,JUNIOR REVERSIBLE HOODED LONG Wintermantel,GuessweißJUNIOR REVERSIBLE HOODED LONG Winterm...,Guess weiß
8,08c47691-4160-41df-81c5-ea108f2ae539,Ellesse,weiß,HOLLINA SHIRT & LEGGING Pyjama Nachtwäsche Set,EllesseweißHOLLINA SHIRT & LEGGING Pyjama Nach...,Ellesse weiß
11,96fc5065-3a31-42f0-bfbd-34ee94324807,Selected,blau,SLHSLIMMARK WASHED Businesshemd,SelectedblauSLHSLIMMARK WASHED Businesshemd,Selected blau
12,04341c9e-4043-4478-9a64-266ac38480b5,Ellesse,schwarz,NURRA FASHION TRUNKS 5 PACK Panties,EllesseschwarzNURRA FASHION TRUNKS 5 PACK Panties,Ellesse schwarz
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,Selected,braun,SLFOLIVE CARDIGAN Strickjacke,SelectedbraunSLFOLIVE CARDIGAN Strickjacke,Selected braun
15,579f4b76-2361-4d2d-9d9a-1190c46e4001,Kaffe,oliv,KAMONNA BLOUSE Langarmshirt Bluse,KaffeolivKAMONNA BLOUSE Langarmshirt Bluse,Kaffe oliv

In [25]:
offers_training_df_zalondo_1['comparison'] = offers_training_df_zalondo_1['comparison1'].str.cat(offers_training_df_zalondo_1['title'],sep=" ")
offers_training_df_zalondo_1.head(6)

,offer_id,brand,color,title,Name,comparison1,comparison
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,Guess,weiß,JUNIOR REVERSIBLE HOODED LONG Wintermantel,GuessweißJUNIOR REVERSIBLE HOODED LONG Winterm...,Guess weiß,Guess weiß JUNIOR REVERSIBLE HOODED LONG Winte...
8,08c47691-4160-41df-81c5-ea108f2ae539,Ellesse,weiß,HOLLINA SHIRT & LEGGING Pyjama Nachtwäsche Set,EllesseweißHOLLINA SHIRT & LEGGING Pyjama Nach...,Ellesse weiß,Ellesse weiß HOLLINA SHIRT & LEGGING Pyjama Na...
11,96fc5065-3a31-42f0-bfbd-34ee94324807,Selected,blau,SLHSLIMMARK WASHED Businesshemd,SelectedblauSLHSLIMMARK WASHED Businesshemd,Selected blau,Selected blau SLHSLIMMARK WASHED Businesshemd
12,04341c9e-4043-4478-9a64-266ac38480b5,Ellesse,schwarz,NURRA FASHION TRUNKS 5 PACK Panties,EllesseschwarzNURRA FASHION TRUNKS 5 PACK Panties,Ellesse schwarz,Ellesse schwarz NURRA FASHION TRUNKS 5 PACK Pa...
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,Selected,braun,SLFOLIVE CARDIGAN Strickjacke,SelectedbraunSLFOLIVE CARDIGAN Strickjacke,Selected braun,Selected braun SLFOLIVE CARDIGAN Strickjacke
15,579f4b76-2361-4d2d-9d9a-1190c46e4001,Kaffe,oliv,KAMONNA BLOUSE Langarmshirt Bluse,KaffeolivKAMONNA BLOUSE Langarmshirt Bluse,Kaffe oliv,Kaffe oliv KAMONNA BLOUSE Langarmshirt Bluse

In [26]:
offers_training_df_aboutyou_1['comparison1'] = offers_training_df_aboutyou_1['brand'].str.cat(offers_training_df_aboutyou_1['color'],sep=" ")
offers_training_df_aboutyou_1.head(6)

,offer_id,brand,color,title,Name,comparison1
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,PIECES,hellblau | Blau,Kleid,PIECEShellblau | BlauKleid,PIECES hellblau | Blau
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,LASCANA,schwarz | mischfarben | Schwarz,Bikinihose,LASCANAschwarz | mischfarben | SchwarzBikinihose,LASCANA schwarz | mischfarben | Schwarz
2,f0328791-9839-4bc1-ac62-78b7515e9601,MAMALICIOUS,beige | Beige,Chino-Hose,MAMALICIOUSbeige | BeigeChino-Hose,MAMALICIOUS beige | Beige
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunde,rosa | Pink,Top / Seidentop,rosemunderosa | PinkTop / Seidentop,rosemunde rosa | Pink
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,PIECES,mischfarben | schwarz | Mischfarben | Schwarz,Kleid,PIECESmischfarben | schwarz | Mischfarben | Sc...,PIECES mischfarben | schwarz | Mischfarben | S...
6,1db3c99c-fc6a-4d30-b916-17c36de9fd14,ELLESSE,weiß | Weiß,Sneaker,ELLESSEweiß | WeißSneaker,ELLESSE weiß | Weiß

In [27]:
offers_training_df_aboutyou_1['comparison'] = offers_training_df_aboutyou_1['comparison1'].str.cat(offers_training_df_aboutyou_1['title'],sep=" ")
offers_training_df_aboutyou_1.head(6)

,offer_id,brand,color,title,Name,comparison1,comparison
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,PIECES,hellblau | Blau,Kleid,PIECEShellblau | BlauKleid,PIECES hellblau | Blau,PIECES hellblau | Blau Kleid
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,LASCANA,schwarz | mischfarben | Schwarz,Bikinihose,LASCANAschwarz | mischfarben | SchwarzBikinihose,LASCANA schwarz | mischfarben | Schwarz,LASCANA schwarz | mischfarben | Schwarz Bikini...
2,f0328791-9839-4bc1-ac62-78b7515e9601,MAMALICIOUS,beige | Beige,Chino-Hose,MAMALICIOUSbeige | BeigeChino-Hose,MAMALICIOUS beige | Beige,MAMALICIOUS beige | Beige Chino-Hose
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunde,rosa | Pink,Top / Seidentop,rosemunderosa | PinkTop / Seidentop,rosemunde rosa | Pink,rosemunde rosa | Pink Top / Seidentop
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,PIECES,mischfarben | schwarz | Mischfarben | Schwarz,Kleid,PIECESmischfarben | schwarz | Mischfarben | Sc...,PIECES mischfarben | schwarz | Mischfarben | S...,PIECES mischfarben | schwarz | Mischfarben | S...
6,1db3c99c-fc6a-4d30-b916-17c36de9fd14,ELLESSE,weiß | Weiß,Sneaker,ELLESSEweiß | WeißSneaker,ELLESSE weiß | Weiß,ELLESSE weiß | Weiß Sneaker

In [28]:
offers_training_df_zalondo_2 = offers_training_df_zalondo_1 [['offer_id', 'comparison', 'brand']]
offers_training_df_zalondo_2.head(10)

,offer_id,comparison,brand
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,Guess weiß JUNIOR REVERSIBLE HOODED LONG Winte...,Guess
8,08c47691-4160-41df-81c5-ea108f2ae539,Ellesse weiß HOLLINA SHIRT & LEGGING Pyjama Na...,Ellesse
11,96fc5065-3a31-42f0-bfbd-34ee94324807,Selected blau SLHSLIMMARK WASHED Businesshemd,Selected
12,04341c9e-4043-4478-9a64-266ac38480b5,Ellesse schwarz NURRA FASHION TRUNKS 5 PACK Pa...,Ellesse
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,Selected braun SLFOLIVE CARDIGAN Strickjacke,Selected
15,579f4b76-2361-4d2d-9d9a-1190c46e4001,Kaffe oliv KAMONNA BLOUSE Langarmshirt Bluse,Kaffe
16,927b22f1-ba0e-43a7-af78-f9c7bc5fe42b,Zizzi schwarz Jerseykleid,Zizzi
19,3bbca9fd-bcad-4486-ab3b-253579ceb42b,Selected schwarz SLFCOSTINA ROLLNECK Strickpul...,Selected
22,665b3cee-58ff-4f34-9c0f-7f20bc1260e7,Selected schwarz SLHBERG Langarmshirt Poloshirt,Selected
24,38fe09fc-9a29-49fb-93f4-9adb62c89a2a,Kaffe mehrfarbig MANU SHIRT DRESS Blusenkleid,Kaffe

In [29]:
offers_training_df_aboutyou_2 = offers_training_df_aboutyou_1 [['offer_id', 'comparison', 'brand']]
offers_training_df_aboutyou_2.head(10)

,offer_id,comparison,brand
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,PIECES hellblau | Blau Kleid,PIECES
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,LASCANA schwarz | mischfarben | Schwarz Bikini...,LASCANA
2,f0328791-9839-4bc1-ac62-78b7515e9601,MAMALICIOUS beige | Beige Chino-Hose,MAMALICIOUS
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunde rosa | Pink Top / Seidentop,rosemunde
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,PIECES mischfarben | schwarz | Mischfarben | S...,PIECES
6,1db3c99c-fc6a-4d30-b916-17c36de9fd14,ELLESSE weiß | Weiß Sneaker,ELLESSE
7,18069589-7d8b-49f5-9d5a-506d1a061719,ELLESSE weiß | dunkelblau | orange | Weiß Spor...,ELLESSE
9,ea0df12f-3b4d-4635-aaf2-503523dafa9b,Free People schwarz | Schwarz Slip 'TAMEEKA',Free People
10,fb56d20d-c973-4f7a-8152-a8bf1f5748f7,BULLBOXER cognac | dunkelblau | Braun Schnürboots,BULLBOXER
14,95799dfe-636a-43c2-bce0-fa022060ab0e,GUESS altrosa | Pink Pullover 'HENRIETTE',GUESS

In [30]:
# cleaning the concateated column by removing special charecters with the help of regex

offers_training_df_zalondo_2['comparison_new'] = offers_training_df_zalondo_2['comparison'].str.replace('[^\w\s]', ' ', regex= True)
offers_training_df_zalondo_2.head(30)

,offer_id,comparison,brand,comparison_new
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,Guess weiß JUNIOR REVERSIBLE HOODED LONG Winte...,Guess,Guess weiß JUNIOR REVERSIBLE HOODED LONG Winte...
8,08c47691-4160-41df-81c5-ea108f2ae539,Ellesse weiß HOLLINA SHIRT & LEGGING Pyjama Na...,Ellesse,Ellesse weiß HOLLINA SHIRT LEGGING Pyjama Na...
11,96fc5065-3a31-42f0-bfbd-34ee94324807,Selected blau SLHSLIMMARK WASHED Businesshemd,Selected,Selected blau SLHSLIMMARK WASHED Businesshemd
12,04341c9e-4043-4478-9a64-266ac38480b5,Ellesse schwarz NURRA FASHION TRUNKS 5 PACK Pa...,Ellesse,Ellesse schwarz NURRA FASHION TRUNKS 5 PACK Pa...
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,Selected braun SLFOLIVE CARDIGAN Strickjacke,Selected,Selected braun SLFOLIVE CARDIGAN Strickjacke
15,579f4b76-2361-4d2d-9d9a-1190c46e4001,Kaffe oliv KAMONNA BLOUSE Langarmshirt Bluse,Kaffe,Kaffe oliv KAMONNA BLOUSE Langarmshirt Bluse
16,927b22f1-ba0e-43a7-af78-f9c7bc5fe42b,Zizzi schwarz Jerseykleid,Zizzi,Zizzi schwarz Jerseykleid
19,3bbca9fd-bcad-4486-ab3b-253579ceb42b,Selected schwarz SLFCOSTINA ROLLNECK Strickpul...,Selected,Selected schwarz SLFCOSTINA ROLLNECK Strickpul...
22,665b3cee-58ff-4f34-9c0f-7f20bc1260e7,Selected schwarz SLHBERG Langarmshirt Poloshirt,Selected,Selected schwarz SLHBERG Langarmshirt Poloshirt
24,38fe09fc-9a29-49fb-93f4-9adb62c89a2a,Kaffe mehrfarbig MANU SHIRT DRESS Blusenkleid,Kaffe,Kaffe mehrfarbig MANU SHIRT DRESS Blusenkleid
25,92b489aa-f1c2-4237-976c-217ea305a1b9,Pieces schwarz PCMAGGI MIDI DRESS Freizeitkleid,Pieces,Pieces schwarz PCMAGGI MIDI DRESS Freizeitkleid
27,e0d26138-64b1-4382-8699-0452b46eef1d,Saucony dunkelblau BABY JAZZ Sneaker low,Saucony,Saucony dunkelblau BABY JAZZ Sneaker low
31,7f2b3621-70a5-4f13-a1c4-e17adef75cc2,Pieces light-blue denim PCDELLY RAW Jeans Sk...,Pieces,Pieces light blue denim PCDELLY RAW Jeans Sk...
34,47f3feb8-6062-4b9b-a58c-9597306a956f,Guess goldfarben SLEEK UNISEX Uhr,Guess,Guess goldfarben SLEEK UNISEX Uhr
37,4d2627ba-850c-4c7d-b8c9-69cec6d3f6e2,Etam rosa EVELINE COMBINAISON DOUDOU Jumpsuit,Etam,Etam rosa EVELINE COMBINAISON DOUDOU Jumpsuit
44,10c2ab26-dccb-401b-b912-44a310d82e74,JAKO dunkelblau ZIP CHAMP 2.0 Fleecepullover,JAKO,JAKO dunkelblau ZIP CHAMP 2 0 Fleecepullover
49,8d8e2c8e-8b87-4d4b-b8d0-171d7e0930d6,Panama Jack dunkelbraun QUINOA CLAY Zehentrenner,Panama Jack,Panama Jack dunkelbraun QUINOA CLAY Zehentrenner
53,ca90ba3b-683a-4c64-8749-b5494a358fcf,Selected oliv-meliert SLFEMMY LS KNIT BUTTONCA...,Selected,Selected oliv meliert SLFEMMY LS KNIT BUTTONCA...
56,1d664b59-0436-4897-a400-3b01fc399d8b,Gestuz mint JILAN DRESS Blusenkleid,Gestuz,Gestuz mint JILAN DRESS Blusenkleid
57,98bcd11b-c045-47e6-9ac9-a0e8a74ea863,Pieces goldfarben PCPANNY BRACELET CUFF Armband,Pieces,Pieces goldfarben PCPANNY BRACELET CUFF Armband
58,1b7e24e2-4278-499e-b594-bc760a577e82,Vero Moda hellgrün NOOS Strickpullover,Vero Moda,Vero Moda hellgrün NOOS Strickpullover
60,9a7e1124-3535-4884-a58f-f77cecbaa530,Bullboxer schwarz Cowboy-/Bikerstiefelette,Bullboxer,Bullboxer schwarz Cowboy Bikerstiefelette
63,eff5cf9d-0f43-4440-ac04-9926cefd60ca,Pieces goldfarben PCKERIME COMBI NECKLACE Hals...,Pieces,Pieces goldfarben PCKERIME COMBI NECKLACE Hals...
65,f0d36b27-1db3-4217-864c-eb4c3c67ef80,LIU JO schwarz MAXI Sneaker low,LIU JO,LIU JO schwarz MAXI Sneaker low
69,ede5a5e1-f4cc-4e98-8926-1f688f5f74ce,Pieces Maternity schwarz PCMCRISTA O NECK DRES...,Pieces Maternity,Pieces Maternity schwarz PCMCRISTA O NECK DRES...
71,0ef22813-a00b-451f-a9b3-aaf22464aa6c,Guess rot TODDLER CORE Langarmshirt,Guess,Guess rot TODDLER CORE Langarmshirt
72,0cc19c5a-f0de-4720-88cb-539c8d705af4,Guess blau HAT WITH LOGO Mütze,Guess,Guess blau HAT WITH LOGO Mütze
79,460ebe14-f411-4c08-a630-85f077fc58f5,Vero Moda schwarz VMKAMMIE MR STRAIGHT Joggin...,Vero Moda,Vero Moda schwarz VMKAMMIE MR STRAIGHT Joggin...
81,971b22f7-9163-48f3-9ec7-8df84d42f833,Vero Moda silberfarben VMEVA PAPERBAG Stoffhose,Vero Moda,Vero Moda silberfarben VMEVA PAPERBAG Stoffhose
82,f9e60ea1-4915-4966-88a5-5c5f8076db65,Vero Moda mint VMLEA O-NECK RAGLAN Strickpullover,Vero Moda,Vero Moda mint VMLEA O NECK RAGLAN Strickpullover

In [32]:
offers_training_df_aboutyou_2['comparison_new'] = offers_training_df_aboutyou_2['comparison'].str.replace('[^\w\s]', ' ', regex= True)
offers_training_df_aboutyou_2.head(30)

,offer_id,comparison,brand,comparison_new
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,PIECES hellblau | Blau Kleid,PIECES,PIECES hellblau Blau Kleid
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,LASCANA schwarz | mischfarben | Schwarz Bikini...,LASCANA,LASCANA schwarz mischfarben Schwarz Bikini...
2,f0328791-9839-4bc1-ac62-78b7515e9601,MAMALICIOUS beige | Beige Chino-Hose,MAMALICIOUS,MAMALICIOUS beige Beige Chino Hose
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunde rosa | Pink Top / Seidentop,rosemunde,rosemunde rosa Pink Top Seidentop
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,PIECES mischfarben | schwarz | Mischfarben | S...,PIECES,PIECES mischfarben schwarz Mischfarben S...
6,1db3c99c-fc6a-4d30-b916-17c36de9fd14,ELLESSE weiß | Weiß Sneaker,ELLESSE,ELLESSE weiß Weiß Sneaker
7,18069589-7d8b-49f5-9d5a-506d1a061719,ELLESSE weiß | dunkelblau | orange | Weiß Spor...,ELLESSE,ELLESSE weiß dunkelblau orange Weiß Spor...
9,ea0df12f-3b4d-4635-aaf2-503523dafa9b,Free People schwarz | Schwarz Slip 'TAMEEKA',Free People,Free People schwarz Schwarz Slip TAMEEKA
10,fb56d20d-c973-4f7a-8152-a8bf1f5748f7,BULLBOXER cognac | dunkelblau | Braun Schnürboots,BULLBOXER,BULLBOXER cognac dunkelblau Braun Schnürboots
14,95799dfe-636a-43c2-bce0-fa022060ab0e,GUESS altrosa | Pink Pullover 'HENRIETTE',GUESS,GUESS altrosa Pink Pullover HENRIETTE
17,7c68e728-c2f6-41a7-b2dc-c311141de46f,JETTE pink | Pink Polo-Shirt,JETTE,JETTE pink Pink Polo Shirt
18,5189ee32-5b19-4052-80b5-39dfc2c5fed4,VERO MODA hellgrün | grasgrün | gelb | Grün Sw...,VERO MODA,VERO MODA hellgrün grasgrün gelb Grün Sw...
20,0104466f-e4e3-4c44-88c9-871ade3b0a4d,QUIKSILVER blau | mischfarben | Blau Sportanzug,QUIKSILVER,QUIKSILVER blau mischfarben Blau Sportanzug
21,59c93954-94b5-4637-b90b-7f67262aecee,Herrlicher blue denim | Blau Jeans 'Pitch',Herrlicher,Herrlicher blue denim Blau Jeans Pitch
23,67099852-3443-486e-9c96-37748ee67c5f,Kaffe schwarz | Schwarz Rock 'Colene',Kaffe,Kaffe schwarz Schwarz Rock Colene
26,a91ad61c-5019-4789-91fe-2dfb175223b3,Envie de Fraise gold | schwarzmeliert | Schwar...,Envie de Fraise,Envie de Fraise gold schwarzmeliert Schwar...
28,0fbbefc5-6ee4-4c4b-8a8f-6a1102c2d19e,VERO MODA schwarz | pastellgrün | rosa | Schwa...,VERO MODA,VERO MODA schwarz pastellgrün rosa Schwa...
29,7a66ee43-3105-4c55-bda8-a9ad945ae741,AG Jeans rostrot | Braun Jeans,AG Jeans,AG Jeans rostrot Braun Jeans
30,4b0bc1d8-bbae-45aa-8670-2494cb658cf5,LASCANA beere | greige | schlammfarben | hellg...,LASCANA,LASCANA beere greige schlammfarben hellg...
32,44270598-50eb-4f0d-ac88-c5c82d340680,VERO MODA schwarz | Schwarz Röhrenhose,VERO MODA,VERO MODA schwarz Schwarz Röhrenhose
33,53801a27-da44-454c-b030-acda03b96428,LASCANA rosa | Pink String,LASCANA,LASCANA rosa Pink String
35,2eed6fff-e3e9-4b53-a802-3075ba1e8157,Zizzi navy | Blau Kleid 'Loui',Zizzi,Zizzi navy Blau Kleid Loui
36,1ae473ae-7acc-44e2-8e07-3ce342eae62a,JETTE gold | Gelb Kette,JETTE,JETTE gold Gelb Kette
38,fd65f87e-c8f0-43ae-8d95-ac1c07dfccfa,MAMALICIOUS weiß | schwarz | Schwarz Badeanzug,MAMALICIOUS,MAMALICIOUS weiß schwarz Schwarz Badeanzug
39,4f767b35-6e84-4dd5-a814-34d9c559efcc,MORE & MORE creme | schwarz | Schwarz Bleistif...,MORE & MORE,MORE MORE creme schwarz Schwarz Bleistif...
40,f4e82e17-a276-4491-8d9d-a41fdd73dbf1,SELECTED HOMME schwarz | Schwarz Schal,SELECTED HOMME,SELECTED HOMME schwarz Schwarz Schal
41,462a987f-4595-4ef8-886d-22bf2795931e,BULLBOXER schwarz | Schwarz Ankle Boots,BULLBOXER,BULLBOXER schwarz Schwarz Ankle Boots
42,19d3a4ad-7083-40c8-be10-32070c290b13,VERO MODA hellgrau | Grau Strickkleid,VERO MODA,VERO MODA hellgrau Grau Strickkleid
43,50fcd08c-458d-4f6a-ae33-cc0e3655f073,LASCANA blau | Blau Caprileggings,LASCANA,LASCANA blau Blau Caprileggings
45,dc55157f-a818-4051-b703-243b8f394e73,SELECTED HOMME burgunder | Rot Pullover 'Cast',SELECTED HOMME,SELECTED HOMME burgunder Rot Pullover Cast

In [33]:
offers_training_df_zalondo_3 = offers_training_df_zalondo_2 [['offer_id', 'comparison_new', 'brand']]
offers_training_df_zalondo_3.head(10)

,offer_id,comparison_new,brand
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,Guess weiß JUNIOR REVERSIBLE HOODED LONG Winte...,Guess
8,08c47691-4160-41df-81c5-ea108f2ae539,Ellesse weiß HOLLINA SHIRT LEGGING Pyjama Na...,Ellesse
11,96fc5065-3a31-42f0-bfbd-34ee94324807,Selected blau SLHSLIMMARK WASHED Businesshemd,Selected
12,04341c9e-4043-4478-9a64-266ac38480b5,Ellesse schwarz NURRA FASHION TRUNKS 5 PACK Pa...,Ellesse
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,Selected braun SLFOLIVE CARDIGAN Strickjacke,Selected
15,579f4b76-2361-4d2d-9d9a-1190c46e4001,Kaffe oliv KAMONNA BLOUSE Langarmshirt Bluse,Kaffe
16,927b22f1-ba0e-43a7-af78-f9c7bc5fe42b,Zizzi schwarz Jerseykleid,Zizzi
19,3bbca9fd-bcad-4486-ab3b-253579ceb42b,Selected schwarz SLFCOSTINA ROLLNECK Strickpul...,Selected
22,665b3cee-58ff-4f34-9c0f-7f20bc1260e7,Selected schwarz SLHBERG Langarmshirt Poloshirt,Selected
24,38fe09fc-9a29-49fb-93f4-9adb62c89a2a,Kaffe mehrfarbig MANU SHIRT DRESS Blusenkleid,Kaffe

In [34]:
offers_training_df_aboutyou_3 = offers_training_df_aboutyou_2 [['offer_id', 'comparison_new', 'brand']]
offers_training_df_aboutyou_3.head(10)

,offer_id,comparison_new,brand
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,PIECES hellblau Blau Kleid,PIECES
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,LASCANA schwarz mischfarben Schwarz Bikini...,LASCANA
2,f0328791-9839-4bc1-ac62-78b7515e9601,MAMALICIOUS beige Beige Chino Hose,MAMALICIOUS
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunde rosa Pink Top Seidentop,rosemunde
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,PIECES mischfarben schwarz Mischfarben S...,PIECES
6,1db3c99c-fc6a-4d30-b916-17c36de9fd14,ELLESSE weiß Weiß Sneaker,ELLESSE
7,18069589-7d8b-49f5-9d5a-506d1a061719,ELLESSE weiß dunkelblau orange Weiß Spor...,ELLESSE
9,ea0df12f-3b4d-4635-aaf2-503523dafa9b,Free People schwarz Schwarz Slip TAMEEKA,Free People
10,fb56d20d-c973-4f7a-8152-a8bf1f5748f7,BULLBOXER cognac dunkelblau Braun Schnürboots,BULLBOXER
14,95799dfe-636a-43c2-bce0-fa022060ab0e,GUESS altrosa Pink Pullover HENRIETTE,GUESS

In [35]:
#applying lowercase to all the columns of the dataset for the ease of the process 

offers_training_df_zalondo_4 = offers_training_df_zalondo_3.apply(lambda x: x.astype(str).str.lower())

In [36]:
offers_training_df_aboutyou_4 = offers_training_df_aboutyou_3.apply(lambda x: x.astype(str).str.lower())

In [37]:
offers_training_df_zalondo_4.head()

,offer_id,comparison_new,brand
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,guess weiß junior reversible hooded long winte...,guess
8,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,ellesse
11,96fc5065-3a31-42f0-bfbd-34ee94324807,selected blau slhslimmark washed businesshemd,selected
12,04341c9e-4043-4478-9a64-266ac38480b5,ellesse schwarz nurra fashion trunks 5 pack pa...,ellesse
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,selected braun slfolive cardigan strickjacke,selected

In [38]:
offers_training_df_aboutyou_4.head()

,offer_id,comparison_new,brand
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,pieces hellblau blau kleid,pieces
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,lascana schwarz mischfarben schwarz bikini...,lascana
2,f0328791-9839-4bc1-ac62-78b7515e9601,mamalicious beige beige chino hose,mamalicious
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunde rosa pink top seidentop,rosemunde
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,pieces mischfarben schwarz mischfarben s...,pieces

In [39]:
offers_training_df_zalondo_6 = pd.DataFrame(offers_training_df_zalondo_4)
offers_training_df_zalondo_6.head(5)

,offer_id,comparison_new,brand
5,02df5ca3-8adc-48fa-bf42-91b41c3ea5a9,guess weiß junior reversible hooded long winte...,guess
8,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,ellesse
11,96fc5065-3a31-42f0-bfbd-34ee94324807,selected blau slhslimmark washed businesshemd,selected
12,04341c9e-4043-4478-9a64-266ac38480b5,ellesse schwarz nurra fashion trunks 5 pack pa...,ellesse
13,346abc38-d9ae-431a-8e6a-64f7bb3ade7e,selected braun slfolive cardigan strickjacke,selected

In [40]:
offers_training_df_aboutyou_6 = pd.DataFrame(offers_training_df_aboutyou_4)
offers_training_df_aboutyou_6.head(5)

,offer_id,comparison_new,brand
0,d8e0dba8-98e8-48db-9850-dd30cff374e0,pieces hellblau blau kleid,pieces
1,c0a743f8-68cf-44dc-80cf-b5edbe70ecb7,lascana schwarz mischfarben schwarz bikini...,lascana
2,f0328791-9839-4bc1-ac62-78b7515e9601,mamalicious beige beige chino hose,mamalicious
3,556e8f61-b1d7-4d72-8bae-d74f9357270b,rosemunde rosa pink top seidentop,rosemunde
4,48b32330-0a6e-4c10-9ef5-c585ac6da701,pieces mischfarben schwarz mischfarben s...,pieces

In [ ]:
# our final 2 dataset are 
# 1- offers_training_df_zalondo_6
# 2- offers_training_df_aboutyou_6

In [41]:
# checking the count value for brand in zalondo

pd.value_counts(offers_training_df_zalondo_6['brand'], sort=True, ascending=False)

vero moda           7910
pieces              4034
guess               3997
selected            2876
ellesse             1998
                    ...
burlington             6
bree                   6
jette fragrances       2
jette                  2
vaay                   2
Name: brand, Length: 83, dtype: int64

In [42]:
# checking the count value for brand in aboutyou

pd.value_counts(offers_training_df_aboutyou_6['brand'], sort=True, ascending=False)

vero moda             12967
guess                  5206
pieces                 4695
lascana                4529
more & more            2500
                      ...
olivia rubin             15
polaroid                 13
mons royale               7
vaay                      3
vero moda wide fit        1
Name: brand, Length: 104, dtype: int64

In [43]:
# taking a single brand from both the dataset for further process

offers_training_df_zalondo_moremore = offers_training_df_zalondo_6[offers_training_df_zalondo_6['brand'] == 'more & more']
offers_training_df_zalondo_moremore.head()

,offer_id,comparison_new,brand
162,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,more & more
325,652b8052-1685-4bff-9e06-1fb428325e2d,more more hellblau t shirt basic,more & more
445,76e3100d-89d1-45b4-8147-a8236c03cf2e,more more offwhite patched bluse,more & more
845,773b0477-be0f-4d26-9183-8dd8928536f7,more more blau blouse bluse,more & more
899,de89698d-56dc-4b60-b453-c719ec37e4da,more more mehrfarbig dress freizeitkleid,more & more

In [44]:
offers_training_df_aboutyou_moremore = offers_training_df_aboutyou_6[offers_training_df_aboutyou_6['brand'] == 'more & more']
offers_training_df_aboutyou_moremore.head()

,offer_id,comparison_new,brand
39,4f767b35-6e84-4dd5-a814-34d9c559efcc,more more creme schwarz schwarz bleistif...,more & more
55,cccef1eb-d8b3-45da-99e5-7b63fc879cdc,more more anthrazit grau jeansjacke,more & more
74,a34d253a-da00-4596-b574-b9bc047e9d09,more more blau blau shirtjacke,more & more
97,34a35756-9fc4-4d38-8da4-1a03637175fe,more more schwarz schwarz plisseerock,more & more
148,c150641e-4b83-4fc3-8c70-9ace7eb93f52,more more schwarz silber schwarz t shirt,more & more

In [45]:
# making both the column in both the dataset as list so that matching can occur with any error

list1 = offers_training_df_zalondo_moremore['comparison_new'].tolist()
list2 = offers_training_df_aboutyou_moremore['comparison_new'].tolist()

In [46]:
# iterating through list1 to extract
# it's closest match from list2

mat1 = []

for i in list1:
    mat1.append(process.extract(i, list2, limit=2))
offers_training_df_zalondo_moremore['matches'] = mat1

offers_training_df_zalondo_moremore.head(10)

,offer_id,comparison_new,brand,matches
162,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,more & more,"[(more more offwhite weiß bluse, 95), (mor..."
325,652b8052-1685-4bff-9e06-1fb428325e2d,more more hellblau t shirt basic,more & more,"[(more more hellblau blau t shirt, 87), (m..."
445,76e3100d-89d1-45b4-8147-a8236c03cf2e,more more offwhite patched bluse,more & more,[(more more creme schwarz schwarz bleist...
845,773b0477-be0f-4d26-9183-8dd8928536f7,more more blau blouse bluse,more & more,"[(more more blau blau bluse, 95), (more ..."
899,de89698d-56dc-4b60-b453-c719ec37e4da,more more mehrfarbig dress freizeitkleid,more & more,"[(more more weiß weiß rock, 86), (more m..."
911,062aefb1-8d37-43a1-b2e7-2181cd65546c,more more mehrfarbig coat klassischer mantel,more & more,"[(more more weiß weiß rock, 86), (more m..."
1472,90990c40-6593-41eb-be19-491f740c8c32,more more grau dress interlock freizeitklei...,more & more,"[(more more anthrazit grau jeansjacke, 86)..."
1489,aabdbab0-62d0-43b8-9cef-4db3be69e9a4,more more weiß bluse top,more & more,"[(more more weiß weiß bluse, 95), (more ..."
1705,3c7c592b-78c1-4af7-9145-4721ae9cd70b,more more blau blouse sleeve bluse,more & more,"[(more more blau blau bluse, 95), (more ..."
2221,b19884ff-a307-4aa6-88e5-c033ad7a0ab1,more more orange dress interlock freizeitkleid,more & more,"[(more more hummer orange hose, 86), (more..."

In [47]:
offers_training_df_zalondo_moremore.to_csv('matching_moremore1.csv')

In [48]:
offers_training_df_zalondo_ellesse = offers_training_df_zalondo_6[offers_training_df_zalondo_6['brand'] == 'ellesse']
offers_training_df_zalondo_ellesse.head()

,offer_id,comparison_new,brand
8,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,ellesse
12,04341c9e-4043-4478-9a64-266ac38480b5,ellesse schwarz nurra fashion trunks 5 pack pa...,ellesse
130,81039b44-547f-4c29-93d0-795561118d8b,ellesse dunkelblau tello swim badeshorts,ellesse
144,c3d5210d-b62f-48df-a10a-364554936dbe,ellesse oliv voodoo t shirt print,ellesse
167,d9ca7533-d4ca-492f-9248-730dc0d81ea4,ellesse offwhite frivola pant jogginghose,ellesse

In [49]:
offers_training_df_aboutyou_ellesse = offers_training_df_aboutyou_6[offers_training_df_aboutyou_6['brand'] == 'ellesse']
offers_training_df_aboutyou_ellesse.head()

,offer_id,comparison_new,brand
6,1db3c99c-fc6a-4d30-b916-17c36de9fd14,ellesse weiß weiß sneaker,ellesse
7,18069589-7d8b-49f5-9d5a-506d1a061719,ellesse weiß dunkelblau orange weiß spor...,ellesse
171,50053f97-20b8-48df-ab3a-d10669f4b998,ellesse weiß himmelblau mandarine weiß t...,ellesse
274,127c7da6-70bb-4ba5-8d36-78bd376ca5f8,ellesse schwarz weiß grenadine mandarine...,ellesse
546,40f909f9-f448-4dff-b723-f5c84ebcb9ba,ellesse schwarz oliv rot orange schwar...,ellesse

In [50]:
list3 = offers_training_df_zalondo_ellesse['comparison_new'].tolist()
list4 = offers_training_df_aboutyou_ellesse['comparison_new'].tolist()

In [51]:
mat2 = []

for i in list3:
    mat2.append(process.extract(i, list4, limit=2))
offers_training_df_zalondo_ellesse['matches'] = mat2

offers_training_df_zalondo_ellesse.head(10)

,offer_id,comparison_new,brand,matches
8,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse b..."
12,04341c9e-4043-4478-9a64-266ac38480b5,ellesse schwarz nurra fashion trunks 5 pack pa...,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse b..."
130,81039b44-547f-4c29-93d0-795561118d8b,ellesse dunkelblau tello swim badeshorts,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse w..."
144,c3d5210d-b62f-48df-a10a-364554936dbe,ellesse oliv voodoo t shirt print,ellesse,[(ellesse weiß dunkelblau orange weiß sp...
167,d9ca7533-d4ca-492f-9248-730dc0d81ea4,ellesse offwhite frivola pant jogginghose,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse s..."
196,1ddc8a25-e3ec-4945-9e7b-956a20112229,ellesse schwarz verta pom beanie 2 pack unisex...,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse b..."
200,41549b94-ec0d-41c9-a312-b14e2511ddbb,ellesse schwarz alente t shirt print,ellesse,"[(ellesse schwarz weiß schwarz t shirt, 87..."
219,1d3f33bc-5d2d-43e4-a26a-6d53cba793c1,ellesse grün trelino track pant jogginghose,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse s..."
250,10dfd143-bb1c-4a81-a8d1-762c64563ec8,ellesse schwarz pinno pack 3 unisex socken,ellesse,"[(ellesse schwarz schwarz socken, 95), (elle..."
353,429548de-bc41-4c2b-b0de-9d97993137f0,ellesse pink freddia langarmshirt,ellesse,[(ellesse weiß dunkelblau orange weiß sp...

In [52]:
offers_training_df_zalondo_ellesse.to_csv('matching_ellesse1.csv')

In [53]:
#adding a temporary file to merge both the dataset to calculate the F1 Score and determine the product matching in 'ellesse' brand

offers_training_df_zalondo_ellesse['tmp'] = 1
offers_training_df_aboutyou_ellesse['tmp'] = 1
df = pd.merge(offers_training_df_zalondo_ellesse, offers_training_df_aboutyou_ellesse, on=['tmp'])
df = df.drop('tmp', axis=1)
df.head(4)

,offer_id_x,comparison_new_x,brand_x,matches,offer_id_y,comparison_new_y,brand_y
0,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse b...",1db3c99c-fc6a-4d30-b916-17c36de9fd14,ellesse weiß weiß sneaker,ellesse
1,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse b...",18069589-7d8b-49f5-9d5a-506d1a061719,ellesse weiß dunkelblau orange weiß spor...,ellesse
2,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse b...",50053f97-20b8-48df-ab3a-d10669f4b998,ellesse weiß himmelblau mandarine weiß t...,ellesse
3,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,ellesse,"[(ellesse weiß weiß sneaker, 86), (ellesse b...",127c7da6-70bb-4ba5-8d36-78bd376ca5f8,ellesse schwarz weiß grenadine mandarine...,ellesse

In [54]:
# removing the columns which are not required

df1= df[['offer_id_x','comparison_new_x', 'offer_id_y', 'comparison_new_y']]
df1.head()

,offer_id_x,comparison_new_x,offer_id_y,comparison_new_y
0,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,1db3c99c-fc6a-4d30-b916-17c36de9fd14,ellesse weiß weiß sneaker
1,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,18069589-7d8b-49f5-9d5a-506d1a061719,ellesse weiß dunkelblau orange weiß spor...
2,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,50053f97-20b8-48df-ab3a-d10669f4b998,ellesse weiß himmelblau mandarine weiß t...
3,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,127c7da6-70bb-4ba5-8d36-78bd376ca5f8,ellesse schwarz weiß grenadine mandarine...
4,08c47691-4160-41df-81c5-ea108f2ae539,ellesse weiß hollina shirt legging pyjama na...,40f909f9-f448-4dff-b723-f5c84ebcb9ba,ellesse schwarz oliv rot orange schwar...

In [55]:
#ellesse brand

from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score

y_true = df1['comparison_new_x']
y_pred = df1['comparison_new_y']

binarizer = MultiLabelBinarizer()

# This should be your original approach
#binarizer.fit(your actual true output consisting of all labels)

# In this case, I am considering only the given labels.
binarizer.fit(y_true)

print('f1 score for ellesse brand:', f1_score(binarizer.transform(y_true), 
         binarizer.transform(y_pred), 
         average='macro'))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:860: UserWarning: unknown class(es) ['8', 'é', 'ö'] will be ignored
  warnings.warn('unknown class(es) {0} will be ignored'

f1 score for ellesse brand: 0.41744453172007884

In [56]:
df1.to_csv('matching_ellesse_f1score.csv')

In [57]:
offers_training_df_zalondo_6_free_people = offers_training_df_zalondo_6[offers_training_df_zalondo_6['brand'] == 'free people']
offers_training_df_zalondo_6_free_people.head(10)

,offer_id,comparison_new,brand
1243,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,free people
2200,40a3e693-fc9e-48c4-8077-a59cb43ff114,free people blau free throw crop sport bh mit ...,free people
2320,f2f3c8d3-b520-4e7b-8439-2ffcb51511ba,free people sand sweetheart strickpullover,free people
2605,9a092770-b5dc-42e4-877d-1025cdc05336,free people schwarz chelsea boot stiefelette,free people
2718,ed7d26eb-fa30-4c78-a1c3-02f6d4b6c5fd,free people sand youre a peach tights,free people
3049,907c4069-4e45-4da3-8637-8da1c1e6d428,free people schwarz callum clogs,free people
3117,4fcea3f0-d2b4-4703-8f22-8bbfd1fb5e95,free people blau set sail bluse,free people
3119,0732e24a-ea06-46ce-a655-c5553bd7e93e,free people hellblau tie dye tee langarmshirt,free people
3188,2b86572f-f23b-4170-8e96-6eb9df5ebf1e,free people grau good karma legging tights,free people
3439,6dc26e10-6ad7-4346-9cc3-2150aadae101,free people schwarz vicente slide zehentrenner,free people

In [58]:
offers_training_df_aboutyou_6_free_people = offers_training_df_aboutyou_6[offers_training_df_aboutyou_6['brand'] == 'free people']
offers_training_df_aboutyou_6_free_people.head(10)

,offer_id,comparison_new,brand
9,ea0df12f-3b4d-4635-aaf2-503523dafa9b,free people schwarz schwarz slip tameeka,free people
87,7d8d04c3-65ab-4188-9550-607edb2394df,free people schwarz grau rosa schwarz kleid,free people
180,eae4a80d-800d-40bb-9dac-8864c8c0a05c,free people schwarz schwarz shorts,free people
524,ffd00fdb-0f07-4ae5-93c7-a13d4b6ecf4c,free people pastellgelb gelb top hayley,free people
588,40c86668-8e78-4106-88e7-c76db4e04497,free people creme beige pullover blue bell,free people
1054,fd86fc9c-3f0c-4520-bc8c-97426a1fca59,free people schwarz rosa pastellgrün pas...,free people
1147,993614f7-1c9c-4c7a-bc5b-f2237df3fef8,free people schwarz schwarz body take a she...,free people
1757,2cc51604-27f4-4f88-9fc6-dfd450c7fde8,free people rosa pink shorts issa,free people
2060,65c9d363-04cc-4619-893d-09a5386b1a39,free people hellbraun braun bh suri,free people
2203,bcac8d2d-7e54-4d9a-95c2-20912eff397a,free people beige weiß grau weiß beige...,free people

In [59]:
offers_training_df_zalondo_6_free_people['tmp'] = 1
offers_training_df_aboutyou_6_free_people['tmp'] = 1
df100 = pd.merge(offers_training_df_zalondo_6_free_people, offers_training_df_aboutyou_6_free_people, on=['tmp'])
df100 = df100.drop('tmp', axis=1)
df100.head(4)

,offer_id_x,comparison_new_x,brand_x,offer_id_y,comparison_new_y,brand_y
0,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,free people,ea0df12f-3b4d-4635-aaf2-503523dafa9b,free people schwarz schwarz slip tameeka,free people
1,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,free people,7d8d04c3-65ab-4188-9550-607edb2394df,free people schwarz grau rosa schwarz kleid,free people
2,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,free people,eae4a80d-800d-40bb-9dac-8864c8c0a05c,free people schwarz schwarz shorts,free people
3,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,free people,ffd00fdb-0f07-4ae5-93c7-a13d4b6ecf4c,free people pastellgelb gelb top hayley,free people

In [60]:
df101= df100[['offer_id_x','comparison_new_x', 'offer_id_y', 'comparison_new_y']]
df101.head()

,offer_id_x,comparison_new_x,offer_id_y,comparison_new_y
0,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,ea0df12f-3b4d-4635-aaf2-503523dafa9b,free people schwarz schwarz slip tameeka
1,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,7d8d04c3-65ab-4188-9550-607edb2394df,free people schwarz grau rosa schwarz kleid
2,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,eae4a80d-800d-40bb-9dac-8864c8c0a05c,free people schwarz schwarz shorts
3,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,ffd00fdb-0f07-4ae5-93c7-a13d4b6ecf4c,free people pastellgelb gelb top hayley
4,8ff4375d-a61e-4c40-9083-8479bcb9d413,free people schwarz keep rolling tank top,40c86668-8e78-4106-88e7-c76db4e04497,free people creme beige pullover blue bell

In [61]:
#free people brand

from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score

y_true = df101['comparison_new_x']
y_pred = df101['comparison_new_y']

binarizer = MultiLabelBinarizer()

# This should be your original approach
#binarizer.fit(your actual true output consisting of all labels)

# In this case, I am considering only the given labels.
binarizer.fit(y_true)

print('f1 score for free people brand:', f1_score(binarizer.transform(y_true), 
         binarizer.transform(y_pred), 
         average='macro'))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:860: UserWarning: unknown class(es) ['0', '1', 'é'] will be ignored
  warnings.warn('unknown class(es) {0} will be ignored'

f1 score for free people brand: 0.5721150176679701

In [67]:
df101.to_csv('matching_free_people_f1score.csv')

In [62]:
offers_training_df_zalondo_6_moremore = offers_training_df_zalondo_6[offers_training_df_zalondo_6['brand'] == 'more & more']
offers_training_df_zalondo_6_moremore.head(10)

,offer_id,comparison_new,brand
162,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,more & more
325,652b8052-1685-4bff-9e06-1fb428325e2d,more more hellblau t shirt basic,more & more
445,76e3100d-89d1-45b4-8147-a8236c03cf2e,more more offwhite patched bluse,more & more
845,773b0477-be0f-4d26-9183-8dd8928536f7,more more blau blouse bluse,more & more
899,de89698d-56dc-4b60-b453-c719ec37e4da,more more mehrfarbig dress freizeitkleid,more & more
911,062aefb1-8d37-43a1-b2e7-2181cd65546c,more more mehrfarbig coat klassischer mantel,more & more
1472,90990c40-6593-41eb-be19-491f740c8c32,more more grau dress interlock freizeitklei...,more & more
1489,aabdbab0-62d0-43b8-9cef-4db3be69e9a4,more more weiß bluse top,more & more
1705,3c7c592b-78c1-4af7-9145-4721ae9cd70b,more more blau blouse sleeve bluse,more & more
2221,b19884ff-a307-4aa6-88e5-c033ad7a0ab1,more more orange dress interlock freizeitkleid,more & more

In [63]:
offers_training_df_aboutyou_6_moremore = offers_training_df_aboutyou_6[offers_training_df_aboutyou_6['brand'] == 'more & more']
offers_training_df_aboutyou_6_moremore.head(10)

,offer_id,comparison_new,brand
39,4f767b35-6e84-4dd5-a814-34d9c559efcc,more more creme schwarz schwarz bleistif...,more & more
55,cccef1eb-d8b3-45da-99e5-7b63fc879cdc,more more anthrazit grau jeansjacke,more & more
74,a34d253a-da00-4596-b574-b9bc047e9d09,more more blau blau shirtjacke,more & more
97,34a35756-9fc4-4d38-8da4-1a03637175fe,more more schwarz schwarz plisseerock,more & more
148,c150641e-4b83-4fc3-8c70-9ace7eb93f52,more more schwarz silber schwarz t shirt,more & more
166,3a6e8097-b600-42fe-811c-3312bc0fa68c,more more türkis rot weiß weiß kurzarm...,more & more
168,288ab3e5-fcb4-402f-8d39-36f9ddb0fdd7,more more schwarz schwarz hose,more & more
205,ec5def4a-c38e-4514-ae49-8a322c03dab9,more more hellgrau weiß weiß langarm bluse,more & more
237,be9409cb-7ad2-4e4e-ace7-47040aaab8d5,more more schwarz schwarz minikleid,more & more
273,82b42faf-0e5b-44aa-8ed4-8664ab53cf96,more more schwarz schwarz abendkleid,more & more

In [64]:
offers_training_df_zalondo_6_moremore['tmp'] = 1
offers_training_df_aboutyou_6_moremore['tmp'] = 1
df200 = pd.merge(offers_training_df_zalondo_6_moremore, offers_training_df_aboutyou_6_moremore, on=['tmp'])
df200 = df200.drop('tmp', axis=1)
df200.head(4)

,offer_id_x,comparison_new_x,brand_x,offer_id_y,comparison_new_y,brand_y
0,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,more & more,4f767b35-6e84-4dd5-a814-34d9c559efcc,more more creme schwarz schwarz bleistif...,more & more
1,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,more & more,cccef1eb-d8b3-45da-99e5-7b63fc879cdc,more more anthrazit grau jeansjacke,more & more
2,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,more & more,a34d253a-da00-4596-b574-b9bc047e9d09,more more blau blau shirtjacke,more & more
3,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,more & more,34a35756-9fc4-4d38-8da4-1a03637175fe,more more schwarz schwarz plisseerock,more & more

In [65]:
df201= df200[['offer_id_x','comparison_new_x', 'offer_id_y', 'comparison_new_y']]
df201.head()

,offer_id_x,comparison_new_x,offer_id_y,comparison_new_y
0,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,4f767b35-6e84-4dd5-a814-34d9c559efcc,more more creme schwarz schwarz bleistif...
1,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,cccef1eb-d8b3-45da-99e5-7b63fc879cdc,more more anthrazit grau jeansjacke
2,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,a34d253a-da00-4596-b574-b9bc047e9d09,more more blau blau shirtjacke
3,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,34a35756-9fc4-4d38-8da4-1a03637175fe,more more schwarz schwarz plisseerock
4,a252fa24-f00a-40a5-a272-e4bc629e3f27,more more offwhite bluse,c150641e-4b83-4fc3-8c70-9ace7eb93f52,more more schwarz silber schwarz t shirt

In [68]:
#more and more brand

from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score

y_true = df201['comparison_new_x']
y_pred = df201['comparison_new_y']

binarizer = MultiLabelBinarizer()

# This should be your original approach
#binarizer.fit(your actual true output consisting of all labels)

# In this case, I am considering only the given labels.
binarizer.fit(y_true)

print('f1 score for more and more brand:', f1_score(binarizer.transform(y_true), 
         binarizer.transform(y_pred), 
         average='macro'))

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:860: UserWarning: unknown class(es) ['7', '8', 'q', 'ä', 'è', 'é', 'ö'] will be ignored
  warnings.warn('unknown class(es) {0} will be ignored'

f1 score for more and more brand: 0.462956523166996

In [69]:
df201.to_csv('matching_moremore_f1score.csv')